ARG SIGNOZ_BASE_IMAGE=signoz/signoz-community:v0.136.1

FROM ${SIGNOZ_BASE_IMAGE} AS base

FROM node:22.22-alpine AS frontend-builder

WORKDIR /app

COPY frontend/ ./frontend/

WORKDIR /app/frontend

RUN corepack enable pnpm

ENV CI=true
RUN pnpm install --frozen-lockfile

RUN pnpm build

FROM base AS final

RUN rm -rf /etc/signoz/web/*
COPY --from=frontend-builder /app/frontend/build/ /etc/signoz/web/
